branch_whitelist = ["main"]

ignore_merge_commits = true

pre_bump_hooks = [
  "sed -i '0,/version = .*/{s/version = .*/version = \"{{version}}\"/}' pyproject.toml",
  "uv sync",
]

post_bump_hooks = [
  "uv run mike deploy --push --update-aliases {{version}} latest",
  "uv run mike set-default --push latest",
  "git push",
  "git push origin v{{version}}",
]

tag_prefix = "v"

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""

[changelog]
path = "CHANGELOG.md"
authors = []
